### ISSUE TITLE
Impossible to access GUI via localhost:9000

### ISSUE THREAD

**Issue by madrumo** [SKenb/AutomatedDoE#1]
Hello,

After reading your recent publication in React. Chem. Eng., I wanted to try Optipus. However, when launching launcher.bat, I cannot access to the GUI ("localhost has refused your connexion"), with port 9000, 8000 nor 8080.

Here is what is prompted in the terminal. Maybe the issue could be related to the failed import of pyDOE2 ?

---- DoE Launcher ----
Starting Frontend
Starting Server
Traceback (most recent call last):
  File "C:\Users\MyUserName\Desktop\AutomatedDoE-main\AutomatedDoE-main\DoE\Server\main.py", line 16, in <module>
    from StateMachine import DoE
  File "C:\Users\MyUserName\Desktop\AutomatedDoE-main\AutomatedDoE-main\DoE\Server\StateMachine\DoE.py", line 4, in <module>
    from StateMachine.Context import ContextDoE
  File "C:\Users\MyUserName\Desktop\AutomatedDoE-main\AutomatedDoE-main\DoE\Server\StateMachine\Context.py", line 2, in <module>
    from Common import ExperimentFactory
  File "C:\Users\MyUserName\Desktop\AutomatedDoE-main\AutomatedDoE-main\DoE\Server\Common\ExperimentFactory.py", line 1, in <module>
    import pyDOE2 as pyDOE
ModuleNotFoundError: No module named 'pyDOE2'

Thank you for your help

**Comment by SKenb** [comment]
Hello,

Thank you for opening this issue.
Have you installed/downloaded the package „pyDOE2“? 

I think it should be something like „pip install pyDOE2“.

BR

**Comment by madrumo** [comment]
Hello, 

You were right, I thought the command to install it was included in the .py files.

Program now works correctly.

Thank you for your answer.
